version: '3.3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:latest
    hostname: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
    networks:
      - network
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:latest
    hostname: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:latest
    hostname: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/senyilma/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/senyilma/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
